# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-16 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.IntegerField(max_length=12)),
            ],
        ),
    ]
