# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='cn',
            field=models.IntegerField(),
        ),
    ]
